name: resumeparser-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - streamlit
      - fastapi
      - uvicorn
      - openai
      - groq
      - langchain
      - langchain-community
      - langchainhub
      - langchain-chroma
      - langchain-google-genai
      - PyPDF2
      - python-dotenv
      - python-multipart
      - gradio-client
      - sentence-transformers
      - streamlit-modal
